import { Character } from "@/types/util/character";

export const Characters: Character[] = [
    {name: 'mai', displayName: 'MAI'},
    {name: 'terry', displayName: 'TERRY'},
    {name: 'vega_mbison', displayName: 'VEGA'},
    {name: 'gouki_akuma', displayName: 'GOUKI'},
    {name: 'ed', displayName: 'ED'},
    {name: 'aki', displayName: 'AKI'},
    {name: 'rashid', displayName: 'RASHID'},
    {name: 'cammy', displayName: 'CAMMY'},
    {name: 'lily', displayName: 'LILY'},
    {name: 'zangief', displayName: 'ZANGIEF'},
    {name: 'jp', displayName: 'JP'},
    {name: 'marisa', displayName: 'MARISA'},
    {name: 'manon', displayName: 'MANON'},
    {name: 'deejay', displayName: 'DEEJAY'},
    {name: 'ehonda', displayName: 'E.HONDA'},
    {name: 'dhalsim', displayName: 'DHALSIM'},
    {name: 'blanka', displayName: 'BLANKA'},
    {name: 'ken', displayName: 'KEN'},
    {name: 'juri', displayName: 'JURI'},
    {name: 'kimberly', displayName: 'KIMBERLY'},
    {name: 'guile', displayName: 'GUILE'},
    {name: 'chunli', displayName: 'CHUNLI'},
    {name: 'jamie', displayName: 'JAMIE'},
    {name: 'luke', displayName: 'LUKE'},
    {name: 'ryu', displayName: 'RYU'},
]